name: Chocolatine
on: [push, pull_request]

jobs:
    check_compilation_and_coding_style:
        runs-on: ubuntu-latest
        # runs-on: epitechcontent/epitest-docker
        steps:
          - name: checkout_repository
            uses: actions/checkout@v5

          - name: ls
            run: ls -la

          - name: grep
            run: grep main
        # steps:
        #   - name: compilation
        #   - run: make | annotate-errors.sh
        # steps:
        #   - name: banana-check-repo
        #   - run:
        # steps:
        #   - name: clean files
        #   - run: make clean
