name: Chocolatine
on:
    push:
      branches-ignores:
        "no-ga/"
    pull_request:
      branches-ignores:
        "no-ga/"
env:
  MIRROR_SSH_URL: "git@github.com:EpitechPGE1-2025/G-DOP-200-RUN-2-1-chocolatine-14.git"
  EXECUTABLES: "chocolatine"

jobs:
    # check_repo:
    #   runs-on: ubuntu-latest
    #   steps:
    #     - name: check_mirror_and_repo
    #     - run: exit 0
          # if: ${{ github.repository != env.MIRROR_SSH_URL}}
          # run: exit 1
    check_compilation_and_coding_style:
        # needs: check_repo
        runs-on: ubuntu-latest
        container:
          image: epitechcontent/epitest-docker
        steps:
          - name: checkout_repository
            uses: actions/checkout@v5

          - name: compile
            run: make
            timeout-minutes: 2

          - name: clean
            run: make clean

          - name: push_on_mirror
            uses: pixta-dev/repository-mirroring-action@v1
            with:
              target_repo_url:
                $MIRROR_SSH_URL
              ssh_private_key:
                ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
