name: Chocolatine
on:
    push:
      branches-ignores:
        "no-ga/"
    pull_request:
      branches-ignores:
        "no-ga/"
env:
  MIRROR_SSH_URL: "git@github.com:EpitechPGE1-2025/G-DOP-200-RUN-2-1-chocolatine-14.git"
  EXECUTABLES: "chocolatine"

jobs:
    check_repo:
      steps:
        - name: check_mirror_and_repo
          run: |
            if ${{ github.repository }} == $MIRROR_SHH_URL then
              continue
            else
              exit 1
            fi
    check_compilation_and_coding_style:
        runs-on: ubuntu-latest
        container:
          image: epitechcontent/epitest-docker
        steps:
          - name: checkout_repository
            uses: actions/checkout@v5

          - name: compile
            run: make
            timeout-minutes: 2

          - name: clean
            run: make clean
        # steps:
        #   - name: compilation
        #   - run: make | annotate-errors.sh
        # steps:
        #   - name: banana-check-repo
        #   - run:
        # steps:
        #   - name: clean files
        #   - run: make clean
